/**
 * Field documentation for the MERCURY input tables, extracted from the
 * Quadrum Data Lake data model (docs/mercury-model/datamodel (1).pdf).
 * Shown as tooltips in the advanced all-fields editor of the Reco
 * new-position form.
 */
export const FIELD_DOCS: Record<string, Record<string, string>> = {
  'core_positions': {
    'Id': 'Unique position identifier.',
    'LoadId': 'Unique dataload identifier.',
    'BookingCenterId': 'Entity producing the reporting data.',
    'CounterpartyBookingCenterId': 'For intercompany transactions, the identifier of the counterparty booking center.',
    'ContractId': 'Identifier of the contract. Can be used to link provisions and their corresponding positions.',
    'CounterpartyId': 'Counterparty of the position. For securities, necessary for short positions in trading book (ARIS). For issued guarantees, deliver the principal.',
    'CounterpartyPIT': 'Point in time.',
    'GuarantorId': 'For covered bonds and received guarantees, deliver the identifier of the guarantor.',
    'GuarantorPIT': 'Point in time.',
    'SecurityId': 'Identifier of the security (list_securities.Id) the position refers to — paired with SecurityPIT.',
    'SecurityPIT': 'Point in time.',
    'LegalAccountNumber': 'Legal account number driving CH reporting - int.',
    'TypeOf': 'For pledged collaterals, date until when the collateral is pledged.',
    'SubType': 'Sub-type of position - varchar(20).',
    'BookAmount': 'Position book amount in reporting currency',
    'Currency': 'ISO 4217 3-letters currency code of the position.',
    'Notional': 'Position notional amount in reporting currency.',
    'MaturityDate': 'Position maturity date of the position (format: YYYY-MM-DD).',
    'StartDate': 'Start date of the position.',
    'InternalReference1': 'Internal reference of the bank system. Used mainly for reconciliation.',
    'InternalReference2': 'Internal reference of the bank system. Used mainly for reconciliation.',
    'InternalReference3': 'Internal reference of the bank system. Used mainly for reconciliation.',
    'DataSource': 'Source of the data loaded in the QDL. Used for internal purpose.',
    'PositionCurrencyBookAmount': 'Position book amount in original currency (positive amount).',
    'EncumberedAmount': 'Position encumbered amount in reporting currency',
    'InternalLendingValue': 'Position internal lending value amount in reporting currency.',
    'PV': 'Position present value in reporting currency. Delivered or computed in Rule',
    'Provision': 'Position provision amount in reporting currency.',
    'ReportingDate': 'Date of reporting',
    'LocationCountry': 'ISO 3166 2-letters country code of the location of the position (coin, notes, tangible assets, securities: location of the depositary, mortgage loan: location of the property (gage immobilier), other assets, other liabilities, equity).',
    'TradingBookFlag': 'Is the position in the trading book: TRUE / FALSE.',
    'IsEdited': 'Manual-edit flag: 1 when the record was created or modified by hand rather than delivered by the source system.',
    'PortfolioId': 'Identifier of the portfolio the position belongs to.',
    'ValueDate': 'Value date of the position.',
  },
  'list_counterparties': {
    'Id': 'Unique counterparty identifier.',
    'PointInTime': 'Point in time.',
    'CreationDate': 'Date at which the record was created or modified.',
    'Name': 'Name of the counterparty.',
    'LegalName': 'Full name of the counterparty. For counterparties with special treatment, use the dedicated name - varchar(100).',
    'LEI': 'Legal entity identifier. For counterparties with special treatment, use the corresponding LEI - varchar(20).',
    'DomicileCountry': 'ISO 3166 2-letters country code of the location of the counterparty.',
    'DomicileCanton': 'For Swiss counterparties, 2-letter code of the canton of location of the counterparty.',
    'HQDomicile': 'ISO 3166 2-letters country code of the location of the head oﬃce of the counterparty.',
    'RelatedPartyType': 'Identification of aﬃliated counterparties. This information can also be delivered in core_positions - Legal ref.: Finma circ. 2015/01 appendix 7 & Finma circ. 2020/01 cm 149-158 - varchar(20).',
    'TypeOf': 'Economic sector/classification of the counterparty from a regulatory point of view - varchar(20).',
    'EconomicActivityType': 'Economic activity type of the counterparty in NOGA 2008 or NACE format.',
    'RatingClass': 'Rating class of the counterparty according to OFR appendix 2 and Finma document Recognised credit rating agencies.',
    'ExternalRatingId': 'Identifier of the external rating as per table list_external_ratings.',
    'ExternalRatingPIT': 'Point in time.',
    'BookingCenterId': 'Deliver the BookingCenterId corresponding to the counterparty.',
    'GroupLEXId': 'Counterparty group for the Large Exposure reporting.',
    'GroupARISId': 'Counterparty group for the ARIS.',
    'Headcount': 'Number of employees of the counterparty.',
    'Turnover': 'Turnover of the counterparty - OFRnew Art.70 al.3.',
    'BalanceSheet': 'Balance sheet size of the counterparty.',
    'SMEFlag': 'Is the counterparty a small or medium enterprise: TRUE / FALSE.',
    'AdequateSupervisionFlag': 'For counterparties which are part of the group: is the entity subject to an adequate surveillance for large exposures. Legal ref.: OFR Art.111a.',
    'RelationshipManagerId': 'Identifier of the relationship manager.',
    'EstablishedRelationshipFlag': 'Is there an established relationship with the counterparty: TRUE / FALSE - Legal ref.: Finma circ. 2015/02 cm 181.',
    'LEXLimitFlag': 'Set to 1 if the limit does apply (not regulated) for a group entity in LEX. Default value: 0. Legal ref.: OFR Art.100 al.8 and Art.111a al.1.',
    'IncomeCurrency': 'ISO 4217 3-letters currency code of the income currency. Legal ref.: OFR art. 66a',
    'Nationality': 'ISO 3166 2-letters country code of the nationality of the counterparty.',
    'ReportingDate': 'Date of reporting',
    'PD': 'Probability of default.',
    'SIScode': 'Institunional sector (SIS Code). Legal ref.: ESA 2010 and MONA_US Notes',
    'IsEdited': 'Manual-edit flag: 1 when the record was created or modified by hand rather than delivered by the source system.',
    'CreditQuality': 'Credit quality step of the counterparty (SA-BIS classification).',
    'RiskEvaluationDate': 'Date of the counterparty\'s last risk evaluation (paired with PD).',
  },
  'list_securities': {
    'Id': 'Unique security identifier.',
    'PointInTime': 'Point in time.',
    'CreationDate': 'Date at which the record was created or modified.',
    'Name': 'Name of the security.',
    'ISIN': 'ISIN code.',
    'BBGTicker': 'Bloomberg ticker.',
    'FIGI': 'Financial instrument global identifier.',
    'SEDOL': 'Stock exchange daily oﬃcial list code.',
    'Currency': 'ISO 4217 3-letters currency code of the security.',
    'IndexFlag': 'Is the security an index: TRUE / FALSE.',
    'MainIndexFlag': 'Is the security part of a main index: TRUE / FALSE - Legal ref.: Finma circ. 2017/07 cm175 + OCre appendix 4.',
    'RevaluationFrequency': 'Revaluation frequency. Legal ref.: Finma circ. 2017/07 cm 177 - char(1).',
    'SNBEligibleFlag': 'SNB eligible security - Finma circ. 2017/07 cm 258.',
    'CMAApproachType': 'Approach used for collectively managed assets - varchar(20).',
    'CMARiskIndicator': 'Synthetic risk indicator of funds treated with the simplified approach (1 to 7) - Finma circ. 2017/07 cm 352 - OCre Art.128 al.1 let.a.',
    'CMASARwFlag': 'Fund under simplified approach elligible for treatment described under cm 352.1 of Finma circ. 2017/07.',
    'RatingClass': 'Rating class of the security according to OFR appendix 2 and Finma document Recognised credit rating agencies.',
    'ExternalRatingId': 'Identifier of the external rating as per table list_external_ratings.',
    'ExternalRatingPIT': 'Point in time.',
    'MaturityDate': 'The maturity date of the security (format: YYYY-MM-DD).',
    'TypeOf': 'Type of the security - varchar(10).',
    'SubType': 'Sub-type of security - varchar(10).',
    'InterestRateId': 'Identifier of the interest rate-related set of information.',
    'IssuerId': 'Identifier of the issuer of the security.',
    'IssuerPIT': 'Point in time.',
    'InvestmentGradeFlag': 'For credit index, is the rating considered investment-grade?',
    'TimeSeriesId': 'Identifier of the security\'s time series.',
    'HQLACategory': 'HQLA category.Computed in rule',
    'LEXGuaranteedFlag': 'Set to 1 for bonds guaranteed according to the definition of OFR Art.118 al.1 let.c and Finma circ. 2019/1 cm 52-62.',
    'ListedType': 'How the security is listed, on a recognized exchange (Finma circ. 2017-07 cm 172,193) or representative market (OFR Art.4 let.g al.3 / 2015/1 annexe 7). varchar(20).',
    'StartDate': 'Issuance date.',
    'ReportingDate': 'Date of reporting',
    'IsEdited': 'Manual-edit flag: 1 when the record was created or modified by hand rather than delivered by the source system.',
  },
};

export const fieldDoc = (table: string, field: string): string | undefined =>
  FIELD_DOCS[table]?.[field];
